In [3]:
import numpy as np

# Arrays in Numpy

## _np.zeros()_

In [4]:
# array of zeros
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## _np.ones()_

In [5]:
# array of ones
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## np.full()

In [6]:
# np.full to create an array of certain size with specified element.
full = np.full(10, 3)
full

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

## np.repeat()

In [7]:
# Similar function can be achieved using np.repeat
repeat = np.repeat(3, 10)
repeat

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [8]:
# Repeat can be used to pass multiple elements
array = np.repeat([0.0, 1.0], 5) # each element repeats 5 times
array

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [9]:
array = np.repeat([1, 2], [2, 4])  # 1 is repeated twice, 2 is repeated 4 times.
array

array([1, 1, 2, 2, 2, 2])

In [10]:
array[1]  # Access array element

np.int64(1)

## Make array from list of elements _np.array()_

In [11]:
elements = [1, 2, 3, 4, 5]
np.array(elements)

array([1, 2, 3, 4, 5])

## _np.arange()_ (similar to python range)

In [12]:
np.arange(10) # Prints 10 values starting from 0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## _np.linspace()_

In [13]:
# A range of evenly spaces values within upper and lower bounds
np.linspace(start=0, stop=10, num=11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# Numpy Data Types
- Python lists are not type constraint, they can store any data type. This is not the same with **numpy arrays**. In Numpy arrays all elements of an array must be of the same type.
These are called _dtypes_.

There are four broad categories of dtypes
- __Unsigned int(uint)__ - always positive integers
- __Signed int(int)__ - positive or negative integers
- __Floats(float)__ - real numbers
- __Boolean(bool)__ - True and False values

There are multiple variation of each dtype depending on the number of bits used for their represetation.
E.g., $ {\tt uint8, unit16, uint32, uint64}$

In case of floats, we have only three types:
${\tt float16, float32, float64}$

```
Note: In Numpy, default dtype is 64 bit (8 bytes), depending on precision required we can downgrade the dtype to 32 to consume twice as less memory, making the algorithm run faster.
```


For more understanding on dtypes: https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html

In [14]:
# np.zeros with dtype parameter
zeros = np.zeros(10, dtype=np.uint8)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

`
Warning: Do mind if that if the utilized dtype is lower than the precision required. Numpy will throw out of bounds error.
`

In [15]:
zeros[0] = 255  # Highest number using 8 bits
print(zeros[0])

# While this will throw error
zeros[0] = 256  # out of bounds for 8 bits

255


OverflowError: Python integer 256 out of bounds for uint8

# Two-Dimensional (2D) Numpy Arrays

## 2D arrays using _np.zeros(), np.ones(), np.full()_

In [16]:
# define a 2d array by passing 2d shapes
zeros = np.zeros((3, 3), dtype=np.float32)
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [17]:
# 2d ones
ones = np.ones((3, 3), dtype=np.uint8)
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [18]:
# 2d fill
full = np.full((3, 3), 2)
full

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

## Create 2D array form list of lists

In [19]:
numbers = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]

numbers = np.array(numbers)
numbers

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 2D array slicing

In [20]:
# Get element from a row and column
print(numbers[0, 2])  # 0th row 2nd column
numbers[0, 2] = 10
numbers

3


array([[ 1,  2, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [21]:
# Python list like slicing in Numpy \
print(numbers[:, 1])
numbers[:2, :] # Get all exclude 2 index of row

[2 5 8]


array([[ 1,  2, 10],
       [ 4,  5,  6]])

# Check array dimensionality _.shape()_

In [22]:
zeros = np.zeros((2, 3), dtype=np.int32)
print(zeros)
print(zeros.shape)

[[0 0 0]
 [0 0 0]]
(2, 3)


# _.random_ in Numpy

## _.random.rand()_
generates random numbers, uniformly distributed between 0 and 1.

In [23]:
np.random.seed(42)  # Setting a seed produces similar results each time
arr = np.random.rand(5, 2)  # generated random number between 0 and 1 of shape (5, 2)
arr

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258]])

## _np.random.randn()_
generates random numbers, from a normal distribution between with the mean of 0. The numbers closer to 0 are more likely to be generated. The generated numbers can be positive or negative.


In [24]:
arr = np.random.randn(5, 2)
arr

array([[-0.46947439,  0.54256004],
       [-0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024],
       [-1.72491783, -0.56228753],
       [-1.01283112,  0.31424733]])

## _np.random.randint()_
generates uniformly distributed random numbers between 0 and 100 (exclusive).

In [25]:
randint = np.random.randint(low=0, high=100, size=(5, 2))
randint

array([[91, 59],
       [79, 14],
       [61, 61],
       [46, 61],
       [50, 54]])

# Numpy Operations

In [31]:
rng = np.arange(5)
rng

array([0, 1, 2, 3, 4])

## Multiplication.

In [32]:
rng * 2

array([0, 2, 4, 6, 8])

## Addition

In [33]:
rng + 2

array([2, 3, 4, 5, 6])

## Subtraction & Division

In [34]:
rng - 2

array([-2, -1,  0,  1,  2])

In [35]:
rng / 2

array([0. , 0.5, 1. , 1.5, 2. ])

## Multiple operation at once

In [36]:
rng = np.arange(5)
(rng - 1) * 3 / 2 + 1  # Notice: result is in float dtype

array([-0.5,  1. ,  2.5,  4. ,  5.5])

## Other useful operations
1. __np.exp()__
2. __np.log()__
3. __np.sqrt()__



In [38]:
vector = [100, 1000, 10000]
# log can be done using log10, log2, log1p, emath.log
np.log10(vector)

array([2., 3., 4.])

In [39]:
vector = [1, 2, 3]
np.exp(vector)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [40]:
vector = [1, 4, 9, 25]
np.sqrt(vector)

array([1., 2., 3., 5.])

# Summarizing operations
1. **.sum()**
2. **.min()**
3. **.max()**
4. **.std()**


In [45]:
pred = np.random.randint(3)
print(pred)
pred.sum()

0


AttributeError: 'int' object has no attribute 'sum'